name: subtree
on:
  push:
    tags:
      - v*
    branches:
      - main

env:
  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_API_TOKEN }}
      - name: 'Install splitsh'
        run: |
          curl -L https://github.com/splitsh/lite/releases/download/v1.0.1/lite_linux_amd64.tar.gz > lite_linux_amd64.tar.gz
          tar -zxpf lite_linux_amd64.tar.gz
          chmod +x splitsh-lite
          echo "$(pwd)" >> $GITHUB_PATH
      - name: 'Split to manyrepo'
        run: find src -maxdepth 2 -name composer.json -print0 | xargs -I '{}' -n 1 -0 bash .github/subtree.sh {} ${{ github.ref }}
