name: Tests

on:
  push:
  pull_request:

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: posix, pcntl
          tools: composer:v2

      - name: Composer install
        run: composer install

      - name: Monorepo validate
        run: composer run monorepo-validate

      - name: Codestyle check
        run: composer run cs-fixer-test

      - name: Static analyze
        run: composer run static-analyze

  tests:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - PHP ${{ matrix.php }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        php: ['8.2', '8.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: posix, pcntl
          tools: composer:v2

      - name: Composer install
        run: composer install

      - name: Tests
        run: composer run test
